### ISSUE TITLE
タスク完了時の効果音が欲しい

### ISSUE THREAD

**Issue by minimadon** [doamomo/todoApp#13]
タスクのチェックボックスをクリックした際にドラゴンクエストのレベルアップ時のような効果音が鳴るようにして欲しいです。
ご検討頂けますと幸いです。よろしくお願い致します。

**Comment by doamomo** [comment]
提案ありがとうございます。
面白かったので早速実装してみました。
READMEにも書きましたが、右上アイコンを押すことで、無音、シンプルな音、豪華な音を切り替えられます。
そのあとタスク完了すると音が鳴ります（音は少し小さめに設定してありますが、ご希望あればおっしゃってください）

**Comment by minimadon** [comment]
@doamomo 様
ご対応ありがとうございます。音を選択できるのはとても良いと思います。グッとモチベーションが上がりました。

もう少しだけリクエストさせて頂いても良いでしょうか？
1. "効果音：魔王魂"の表示を画面左下→画面右下にすることはできますでしょうか？プロジェクト追加時に誤ってクリックしてしまうかもしれません。
2. "効果音：魔王魂"をクリックした際に魔王魂様のWebサイトが表示されますが、Webブラウザの別タブで表示させることができますでしょうか？
例) `<a href="https://maou.audio/" target="_blank" rel="noopener noreferrer">効果音：魔王魂</a>`
3. 右上アイコン🔔の切り替え状態をCookie等に残しておくことはできますでしょうか？

ご検討頂けますと幸いです。

**Comment by doamomo** [comment]
ご利用の報告、こちらこそ感謝いたします！
1,2については簡単な修正事項なので、今すぐ行います。
3,についてはその後に行います。少々お待ちくださいませ。

**Comment by doamomo** [comment]
1,2,3全項目の修正を完了しました。
ご確認いただければ幸いです。

**Comment by minimadon** [comment]
お手数をお掛け致しました。ご対応ありがとうございます。
1, 2につきましては確認がとれましたのでOKとなっております。
3につきましては、Google Chromeブラウザにてブラウザアプリを完全終了すると保存したCookie(todoSoundType)が無効になる現象を確認致しましたので、#14 にてプルリクエストを作成致しました。お手数をお掛け致しますが、ご確認のほど、よろしくお願い致します。

改めまして、ご対応ありがとうございました。
