### ISSUE TITLE
README.mdを追加して環境構築手順を記載して欲しい

### ISSUE THREAD

**Issue by minimadon** [doamomo/todoApp#3]
私はUbuntu Serverにて、
- DB設計.txtを見ながらMariaDB(MySQL)にデータベース作成・テーブル作成
- 不足しているPHPモジュールをインストール

などを手探り感覚で行い、実行環境を構築しました。

例えばですが、doamomo / todoApp / README.md ファイルを作成して、実行環境構築手順を記載してみてはいかがでしょうか？
例) https://github.com/oreilly-japan/deep-learning-from-scratch

README.mdファイルを作成することで、実行環境構築のハードルが下がり、利用者が多くなればよりよいアプリになるかと思っています。

**Comment by doamomo** [comment]
構築のためにお手数をおかけしました。
そこまでして使ってみていただいたことに、まずは感謝いたします。

今後の利用者の為にも、手順の記載を試みてみようと思います。
参考例を見ながら、再現しやすいドキュメントにできればと思います。

**Comment by doamomo** [comment]
お待たせしました。
変更点
・README.mdファイルを追加し、構築の難易度を下げた。
・DB設計.txtファイルにMySQLでのコピペ用のソースを追記し、テーブル作成が容易になるよう配慮した。
になります。
READMEを書くいい機会になりました。
ご丁寧にありがとうございます、さらにこうしたほうが良いという点があればお知らせ頂けると嬉しく思います。

**Comment by minimadon** [comment]
@doamomo 様
ご回答・ご対応ありがとうございます。
READMEを拝読しまして、概要等も把握することができ、とても良いと思います。
また、DB設計.txtファイルに記載されたCREATE TABLE文でテーブルを作り直して利用しております。安心して利用できます。
重ねてお礼申し上げます。
しばらくローカル環境で使用しておりましたが、グローバル環境(VPS等)で利用していきたいと思います。

当方からの要望としてIssueを立てておりましたので、Closeとさせて頂きます。
