### ISSUE TITLE
マルチユーザー対応のためテーブル定義変更

### ISSUE THREAD

**Issue by minimadon** [doamomo/todoApp#56]
ver1.7.0を利用しておりますが、プライベートとビジネスで使い分け(切り替え)できるような機能を実装して欲しいと考えておりました。
ですが、マルチユーザー対応して頂けますとより汎用的に利用できるのではないかと考えております。
※プライベート用ユーザーIDとビジネス用ユーザーIDを登録して利用する形です。

また、TODOアプリを表示するたびにログイン要求されてしまいますと手間が掛かりますので、オプションとしてCookieへログイン情報を書き出し1週間〜60日ごとのログイン要求という形にするのがベストと考えております。

後ほど、ER図と画面イメージを提示致します。
大変お手数をお掛け致しますが、ご検討頂きまして、マイルストーン・期限は設けず、方向性のみコメント頂けますと幸いです。
もし、実装するといった方向に進んだ場合は、私( @minimadon )にアサインして頂けますと幸いです。

よろしくお願い致します。

**Comment by minimadon** [comment]
大変恐縮ですが、私( @minimadon )にて更新致しましたER図を貼付致します。

プロジェクトごとに所有者ユーザーIDを持ち、非公開/公開を切り替える事ができるような形にしております。
また、Twitterのようにユーザーアイコンを登録できるようにしております。

変更点は以下の通りです。
1. 'user' テーブルを追加
2. 'project' テーブルに [所有者ユーザーID]、[所有者のみ閲覧可/公開] 列を追加
3. 'skin' テーブルに [ユーザーID] 列を追加
4. ’skin' テーブルの [キー] 列にてパフォーマンス改善のための '*-hash' パターン追加することを追記
※ver1.7.0では画像データのSHA256ハッシュ値をWebページ表示の度に取得しておりますが、あらかじめSHA256ハッシュ値をデータベースに保存しておくことでサーバー負荷を軽減します。
5. 'skin' テーブルの [キー] 列にてユーザーアイコン画像データのパターン(user-icon*)を追記

![erd](https://user-images.githubusercontent.com/90094327/140867523-43b6fe55-8eb5-4c96-a568-d1a0e8eb3e7f.png)

以上、よろしくお願い致します。

**Comment by doamomo** [comment]
マルチユーザー対応、良いですね！
同じサーバー、データベースを用いながらのシーンによる使い分けも可能になります。
cookie期限は…色々なサービスを使っている体感ですが、2~3週間ほどで如何でしょうか？
画面遷移や、パスワード登録、変更、再登録機能などどこまで考慮するか悩みますが、画面イメージ後ほど出していただけるとのことなので、いったん待機しておきますね。

**Comment by minimadon** [comment]
@doamomo 様
コメントありがとうございます。
cookie期限を設定するとともに、バックエンド(PHP・MySQL(MariaDB))においても期限をチェックできる方が良さそうです。
また、マルチユーザー対応に伴い通知(パスワード変更のお願い等)の重要性が高まるため、以下のようにER図を更新致しました。
※赤文字の箇所がmasterブランチと異なる箇所(マルチユーザー対応分)となります。

確認するポイント：
1. プロジェクト毎に[公開/非公開]を選択でき、公開プロジェクトのタスクにつきましてはトップページ等に[最近作成されたタスク]、[最近完了したタスク]として表示可能としております。
2. 公開プロジェクトのタスクへログインユーザーによるリアクション(いいね等)を行えるようにしております。
3. ユーザーのアイコン画像データを登録できるようにしております。1.に記載しておりますトップページ等での表示に用いる形となっております。
4. TODOアプリ アップデート情報などの[お知らせ]を表示するためのテーブルを追加しております。
![erd](https://user-images.githubusercontent.com/90094327/141720203-4f47a46d-98a7-40ba-8cf6-fe7e06efcd0c.png)

お手数をお掛け致しますが、ご確認のほど、よろしくお願い致します。

**Comment by minimadon** [comment]
@doamomo 様
当Issueにつきまして、タイトルを変更致しました。
画面イメージにつきましては、別途新規Issueを作成しまして検討を行う形とさせて頂きます。

**Comment by doamomo** [comment]
@minimadon 様
ER図、その他確認させていただきました。
このようにまとめていただけると、方向性が見えて助かります。
この改修後にはチームでも利用可能なアプリとなりますね。
別途issueについて、承知しました。お待ちしております！

**Comment by minimadon** [comment]
@doamomo 様
ご確認ありがとうございます。
お手数をお掛け致しますが、当Issueにつきまして、私( @minimadon )へアサインをお願い致します。

**Comment by minimadon** [comment]
@doamomo 様
アサイン対応ありがとうございます。

Pull Request #59 では下図の赤字箇所のとおり一部テーブル定義を変更しております。

1. user_notificationテーブル user_notification列 型変更 int(11) → bigint
2. user_notificationテーブル is_read列 表現修正 "[未読/既読]" →  "[既読/未読]" (true/falseの順に記載)
3. userテーブル user_name列 ユニーク制約追加
4. userテーブル created_datetime列, password_updated_datetime列 追加
5. sessionテーブル session_id列 型変更 int(11) → bigint
6. skinテーブル skin_id列 追加 (テーブル先頭列にID列を設けて他のテーブルと同様の扱いに変更)
7. skinテーブル user_id, key, row_index列 ユニーク制約追加
8. task_reactionテーブル task_reaction_id列 追加 (6.と同様の変更)
9. task_reactionテーブル task_id, user_id, material_icon列 ユニーク制約追加

![erd](https://user-images.githubusercontent.com/90094327/142565576-10d0bb92-b3ff-4d08-8c1b-e76789c0d79d.png)

よろしくお願い致します。

**Comment by minimadon** [comment]
Pull Request #59 がmasterブランチへマージされましたので、Closeとさせて頂きます。
ご確認等、ありがとうございます。
