### ISSUE TITLE
ファイルツリー構造を変更したい

### ISSUE THREAD

**Issue by gtgjpj** [doamomo/todoApp#65]
#64 対応の前準備としまして以下のようになっているファイルツリー構造を変更したいと考えております。
ご検討頂けますでしょうか？
もし、他のファイルツリー構造が良いという場合はコメント頂ければと存じます。よろしくお願い致します。

のちに todoApp ディレクトリ直下に docker-compose.yml や php フォルダを置く形になってきます。

2022/11/11 時点(変更前)：
<pre>
todoApp
│
└─todo
    │  base.css
    │  class.puml
    │  erd.puml
    │  jquery-3.5.1.min.js
    │  knockout-3.5.1.js
    │  README.md
    │
    ├─srcFolder
    │  │  deploy_database.php
    │  │  index.php
    │  │  main.css
    │  │  main.js
    │  │  post.php
    │  │  SQL.php
    │  │
    │  ├─config
    │  │  .gitignore
    │  │  DB-example.php
    │  │
    │  └─sound
    │      great.mp3
    │      simple.mp3
    │
    └─test
        └─js
            example.html
            example.js
            viewmodel.html
            viewmodel.js
</pre>

変更後：
<pre>
todoApp
│  .gitignore
│  README.md
│
├─documents
│  class.puml
│  erd.puml
│
├─htdocs
│   │  deploy_database.php
│   │  index.php
│   │  post.php
│   │  SQL.php
│   │
│   ├─config
│   │  DB-example.php
│   │
│   └─static
│      │
│      ├─css
│      │  base.css
│      │  main.css
│      │
│      ├─js
│      │  jquery-3.5.1.min.js
│      │  knockout-3.5.1.js
│      │  main.js
│      │
│      └─media
│          great.mp3
│          simple.mp3
│    
└─test
    └─js
        example.html
        example.js
        viewmodel.html
        viewmodel.js

**Comment by doamomo** [comment]
コメント、提案ありがとうございます。
余計な階層がなくなり、役割に応じたフォルダがわかりやすく作られていて良さそうですね！
htdocsの中にアプリをまとめ、staticの中にクライアント側のソースがまとまっており、見やすくも感じます

このとおり出来たらなと思います
現在体調不良の為、作業の方お願いしてもよろしいでしょうか？

**Comment by gtgjpj** [comment]
コメント返信ありがとうございます。
承知致しました。こちらで対応いたします。
対応は先行して行いますが、当Issueにありますアサイン(Assignees)を私に割り当てて頂ければと存じます。
まずは、体調回復を優先されてくださいませ。

なお、中の人は急激な気温変化に伴い、半袖ハーフパンツでございます。
今年は気温変化・天候変化・気圧変化、それぞれが通常と異なりますので、ご自愛下さいませ。

**Comment by gtgjpj** [comment]
以下のレポジトリにてファイルツリー構造変更対応を行いました。
https://github.com/gtgjpj/todoApp/tree/refactor_file_structure

Webサーバーに置くファイルは htdocs フォルダの中のみとなります。
#64 の対応では README.md ファイルと同じ階層に
1. docker-compose.yml ファイル : "docker compose up -d" コマンドでLAMP環境を構築するdocker用ファイル
2. init_dot_env.sh ファイル : htdocs フォルダ内に docker compose で構築したLAMP側から ファイル書き込みを許可させるためのスクリプトファイル(TODOアプリでは使用しないと思われます)
3. php フォルダ : php と apache を構築するためのdocker用ファイル群を置きます
4. その他 : 初期MySQLユーザー作成および初期データベース作成を行うSQLファイルを作成予定です

お手数をお掛け致しますが、ご確認の程、よろしくお願い致します。

**Comment by gtgjpj** [comment]
追記：master ブランチにマージすると困る場合がありますので、Pull Request を行いませんでした。
support_docker ブランチ等を作成して頂きましたら、そちらへ Pull Request を行うように致します。
よろしくお願い致します。

**Comment by doamomo** [comment]
対応遅くなりました
suppport_docker ブランチ作成の方、行わせていただきます
明日18日までを目途に行う予定ですが、間に合わない際は連絡させていただきます

**Comment by gtgjpj** [comment]
@doamomo 
コメントありがとうございます。
特に期限を設けておりませんので、間に合わなくても問題ございません。

例えばですが、Git Bash ですと、以下のコマンド入力で新しいブランチをGitHub上のレポジトリに作ることができます。
````
~/workspace/todoApp $ git branch support_docker
~/workspace/todoApp $ git switch support_docker
~/workspace/todoApp $ git push --set-upstream origin support_docker
~/workspace/todoApp $ git branch -a
  master
* support_docker
  remotes/origin/master
  remotes/origin/support_docker
~/workspace/todoApp $
````
上記を参考にSourceTreeでも同じような操作ができるかどうか確認してみると良いかと思います。

作業ディレクトリの中身をmasterブランチのものに戻したいときは、
````
~/workspace/todoApp $ git switch master
~/workspace/todoApp $ git branch -a
* master
  support_docker
  remotes/origin/master
  remotes/origin/support_docker
~/workspace/todoApp $
````
で戻れるかと思います。

よろしくお願い致します。

**Comment by doamomo** [comment]
@gtgjpj 
情報ありがとうございます
現在ブランチの作成を試みまして、support_dockerブランチ作成できたかと思われます
思っていたものと違った場合はお伝えいただけると幸いです

**Comment by gtgjpj** [comment]
@doamomo 
ご対応ありがとうございます。バッチリです。
Pull Request #66 を作成しておりましたが、すでにマージして頂いたようで、ありがとうございます。

**Comment by gtgjpj** [comment]
docker compose による 仮組みLAMP 環境にて動作確認できましたのでCloseとさせて頂きます。ご対応ありがとうございました。
support_docker ブランチにつきましては、 #64 がクローズされるまでブランチを維持して頂ければと存じます。
