### ISSUE TITLE
プロジェクトの色分け

### ISSUE THREAD

**Issue by minimadon** [doamomo/todoApp#7]
ver1.3.3にて、「今日」「明日」「それ以降」「完了済み」「期限超過」を選択した場合に、タスクリストのアイテムが表示されますが、それぞれのアイテムがどのプロジェクトのものであるかわかりにくい場合があります。
下図のように色分けを行う事で便利になりそうな気がしますが、いかがでしょうか？
<img width="613" alt="project_color" src="https://user-images.githubusercontent.com/90094327/132275385-3de67c70-a787-4a9f-9d51-1b8752d9517c.png">

お手数をお掛け致しますが、ご検討頂けますと幸いです。

**Comment by doamomo** [comment]
図も添えての提案ありがとうございます！
こちらからも提案なのですが、要素全体に色を付けるのではなく
・プロジェクトのラベルの部分
・タスクの一部（左端チェック部分など）
のみ色を変えるというのはいかがでしょうか！

**Comment by minimadon** [comment]
ご提案頂いた内容、とても良いと思います。(Coolだと思います。)
お手数をお掛け致しますが、ご対応頂けますと幸いです。よろしくお願い致します。

**Comment by minimadon** [comment]
当Issueにつきまして、私にAssignして頂けますでしょうか？
ご検討頂けますと幸いです。

Assignする方法につきましては以下のリンク先をご覧下さいませ。
https://docs.github.com/ja/issues/tracking-your-work-with-issues/managing-issues/assigning-issues-and-pull-requests-to-other-github-users

**Comment by minimadon** [comment]
ご対応ありがとうございます。
こちらでのコーディング(試作)および動作確認ができましたら、プルリクエストを行います。よろしくお願い致します。

**Comment by minimadon** [comment]
プルリクエスト #17 にてご確認頂きましてありがとうございます。
私が変更した箇所のコードをもう少しきれいに安全にしたいと思っております。ちょこちょこプルリクエスト作成してお手数をお掛けすることになりますが、お付き合い頂けますと嬉しく思います。
当Issueにつきましては、@doamomo 様によるプルリクエストのマージが完了しましたので、Closeさせて頂きます。

ありがとうございます。
