### ISSUE TITLE
ダークモード対応について検討して欲しい

### ISSUE THREAD

**Issue by minimadon** [doamomo/todoApp#8]
PCの周囲が暗い環境では、ダークモードがあると見やすい場合があります。
そこで、ダークモードの仕様・実装について検討して頂ければと思います。
下図はver1.3.3の画面を色反転したものになります。いかがでしょうか？
<img width="616" alt="darkmode" src="https://user-images.githubusercontent.com/90094327/132319045-c7a2c9db-aaf1-43e5-b0f2-74986aaff763.png">

お手数をお掛け致しますが、ご検討頂けますと幸いです。

**Comment by doamomo** [comment]
ver1.4.0にてダークモードに対応しました！
右下に表示されるボタンでモードの切り替えが可能です
またcookieに状態を保存する設定になっております

**Comment by minimadon** [comment]
ご返信・ご対応ありがとうございます。
ver1.4.0にて、PC、Android、iOSでそれぞれ確認致しました。
Androidでは切り替えボタンが表示されませんでしたが、Androidシステム設定のダークモードON/OFFが自動的に反映されており、問題ありませんでした。
重ねて御礼申し上げます。Closeと致します。
